### ISSUE TITLE
Panic on nowdoc string literal

### ISSUE THREAD

**Issue by sergey-shambir** [VKCOM/noverify#327]
Panic happens when parsing class which contains nowdoc function argument.
It's enough to remove single quotes to stop panic (i.e. heredoc doesn't cause panic, only nowdoc does).

## Code Example

```php
<?php
declare(strict_types=1);

namespace DoctrineMigrations;

final class Version20191231232355 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql(
            <<<'SQL'
            SELECT login, password FROM user WHERE login LIKE '%admin%'
            SQL
        );
    }

    public function down(Schema $schema): void
    {
    }
}
```

See also https://www.php.net/manual/en/language.types.string.php#language.types.string.syntax.nowdoc

## Actual Behavior

Panic happens:

```
2019/12/30 15:07:40.336480 Failed parsing /home/sweet/home/Version20191231232355.php: Panic while parsing /home/sweet/home/Version20191231232355.php: runtime error: index out of range [0] with length 0

Stack trace: goroutine 134 [running]:
runtime/debug.Stack(0xc002d96ce8, 0x9c46c0, 0xc0024b4fc0)
        /snap/go/4901/src/runtime/debug/stack.go:24 +0x9d
github.com/VKCOM/noverify/src/linter.ParseContents.func1(0xc0017c46c0, 0x53, 0xc002d99e10)
        /home/sweet/home/src/github.com/VKCOM/noverify/src/linter/parser.go:74 +0x6e
panic(0x9c46c0, 0xc0024b4fc0)
        /snap/go/4901/src/runtime/panic.go:679 +0x1b2
github.com/VKCOM/noverify/src/php/parser/scanner.(*Lexer).createToken(0xc000d202d0, 0xc002d96f3c, 0x0, 0x0, 0x1)
        /home/sweet/home/src/github.com/VKCOM/noverify/src/php/parser/scanner/lexer.go:148 +0x2bf
github.com/VKCOM/noverify/src/php/parser/scanner.(*Lexer).Lex(0xc000d202d0, 0xadc100, 0xc003625500, 0xe048)
        /home/sweet/home/src/github.com/VKCOM/noverify/src/php/parser/scanner/scanner.go:8689 +0x3a1c
github.com/VKCOM/noverify/src/php/parser/php7.(*Parser).Lex(0xc0029e5fb0, 0xc003625500, 0xe048)
        /home/sweet/home/src/github.com/VKCOM/noverify/src/php/parser/php7/parser.go:43 +0x44
github.com/VKCOM/noverify/src/php/parser/php7.yylex1(0xae05c0, 0xc0029e5fb0, 0xc003625500, 0xe048, 0x4a)
        yaccpar:119 +0x56
github.com/VKCOM/noverify/src/php/parser/php7.(*yyParserImpl).Parse(0xc003625500, 0xae05c0, 0xc0029e5fb0, 0x0)
        yaccpar:204 +0x4e26b
github.com/VKCOM/noverify/src/php/parser/php7.yyParse(...)
        yaccpar:153
github.com/VKCOM/noverify/src/php/parser/php7.(*Parser).Parse(0xc0029e5fb0, 0xc0029e5fb0)
        /home/sweet/home/src/github.com/VKCOM/noverify/src/php/parser/php7/parser.go:72 +0x94
github.com/VKCOM/noverify/src/linter.ParseContents(0xc0017c46c0, 0x53, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/sweet/home/src/github.com/VKCOM/noverify/src/linter/parser.go:102 +0x4ed
github.com/VKCOM/noverify/src/linter.doParseFile(0xc0017c46c0, 0x53, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, ...)
        /home/sweet/home/src/github.com/VKCOM/noverify/src/linter/parser.go:462 +0xab
github.com/VKCOM/noverify/src/linter.ParseFilenames.func3(0xc0017c4660, 0xc0017c4601, 0xc000c70a20, 0xc0022b78f0)
        /home/sweet/home/src/github.com/VKCOM/noverify/src/linter/parser.go:441 +0x1bb
created by github.com/VKCOM/noverify/src/linter.ParseFilenames
        /home/sweet/home/src/github.com/VKCOM/noverify/src/linter/parser.go:438 +0x21c
```

## Expected Behavior

File parsed without panic.

**Comment by quasilyte** [comment]
Now both heredoc and nowdoc can be parsed with indented ending markers.
